export const Images = {
    addButton: require('../resources/addButton.png'),
    calendar: require('../resources/calendar.png'),
    calendarSelected: require('../resources/calendarSelected.png'),
    person_ic: require('../resources/person_ic.png'),
    editButton: require('../resources/editButton.png'),
    close: require('../resources/close.png'),
    call: require('../resources/call.png'),
    navigate: require('../resources/navigate.png'),
    map: require('../resources/map.png'),
    mapView: require('../resources/mapView.png'),
    list: require('../resources/list.png'),
    location: require('../resources/location.png'),
    elliotLugo: require('../resources/elliotLugo.png'),
    diagnosis: require('../resources/diagnosis.png'),
    notes: require('../resources/notes.png'),
    visits: require('../resources/visits.png'),
    threeDotButton: require('../resources/threeDotButton.png'),
    listView: require('../resources/listView.png'),
    time: require('../resources/time.png'),
    patient: require('../resources/patient.png'),
    pin: require('../resources/pin.png'),
    secureAcessImage: require('../resources/secureAccessImg.png'),
    verificationCodeImage: require('../resources/verificationcodeImg.png'),
    secureImg: require('../resources/secureImg.png'),
    mapImg: require('../resources/mapImg.png'),
    planImg: require('../resources/planImg.png'),
    welcomeScreenImg: require('../resources/welcomeScreenImg.png')

    //MoreScreen
    visitLog: require('../resources/visitLog.png'),
    milesLog: require('../resources/milesLog.png'),
    savedPlaces: require('../resources/savedPlaces.png'),
    accessCode: require('../resources/accessCode.png'),
    setting: require('../resources/setting.png'),
    legal: require('../resources/legal.png'),
    more: require('../resources/more.png'),
};
