export const Images = {
    addButton: require('../resources/addPatient.png'),
    calendar: require('../resources/calendar.png'),
    calendarSelected: require('../resources/calendarSelected.png'),
    person_ic: require('../resources/person_ic.png'),
    editButton: require('../resources/edit.png'),
    close: require('../resources/close.png'),
    call: require('../resources/call.png'),
    navigate: require('../resources/navigate.png'),
    map: require('../resources/map.png'),
    mapView: require('../resources/mapView.png'),
    list: require('../resources/list.png'),
    location: require('../resources/location.png'),
    elliotLugo: require('../resources/elliotLugo.png'),
    diagnosis: require('../resources/diagnosis.png'),
    notes: require('../resources/notes.png'),
    visits: require('../resources/visits.png'),
    threeDotButton: require('../resources/threeDotButton.png'),
    listView: require('../resources/listView.png'),
    time: require('../resources/time.png'),
    patient: require('../resources/patient.png'),
    pin: require('../resources/pin.png'),
    secureAccess: require('../resources/secureAccess.png'),
    verificationCode: require('../resources/verificationcode.png'),
    secureData: require('../resources/secure.png'),
    viewMap: require('../resources/viewmap.png'),
    planDay: require('../resources/plan.png'),
    welcomeScreen: require('../resources/welcomeScreen.png'),
    //MoreScreen
    visitLog: require('../resources/visitLog.png'),
    milesLog: require('../resources/milesLog.png'),
    savedPlaces: require('../resources/savedPlaces.png'),
    accessCode: require('../resources/accessCode.png'),
    setting: require('../resources/setting.png'),
    legal: require('../resources/legal.png'),
    more: require('../resources/more.png'),
};
